name: Publish

# on:
#   release:
#     types: [published]

on:
  push:
    branches:
      - main

jobs:
  apply-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install -g github-label-sync

      - name: Set permissions for script
        run: chmod +x script/apply-labels.sh

      - name: Run apply-labels.sh
        env:
          GH_TOKEN: ${{ secrets.PELAGORNIS_PAT }}
        run: script/apply-labels.sh
