name: Apply Labels to All Repositories

on:
  push:
    paths:
      - 'labels.json'

jobs:
  apply_labels:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Apply Labels to All Repositories
      env:
        GITHUB_TOKEN: ${{ secrets.PELAGORNIS }}  # PAT Token
      run: |
        #!/bin/bash

        # Organization name
        ORG_NAME="pelagornis"
        LABELS_FILE="labels.json"

        # Get all repositories in the organization
        repos=$(curl -s \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          "https://api.github.com/orgs/${ORG_NAME}/repos?per_page=100")

        # Parse labels from labels.json
        labels=$(cat ${LABELS_FILE} | jq -c '.[]')

        # Loop through all repositories
        for repo in $(echo "${repos}" | jq -r '.[].name'); do
          echo "Applying labels to ${repo}..."

          # Loop through all labels
          for label in ${labels}; do
            label_name=$(echo $label | jq -r '.name')
            label_color=$(echo $label | jq -r '.color')
            label_description=$(echo $label | jq -r '.description')

            # GitHub API URL for repository labels
            labels_url="https://api.github.com/repos/${ORG_NAME}/${repo}/labels"

            # Check if label already exists
            label_exists=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
              "${labels_url}" | jq -r --arg label_name "${label_name}" \
              '.[] | select(.name == $label_name) | .name')

            if [[ "$label_exists" == "$label_name" ]]; then
              echo "Label '${label_name}' already exists in ${repo}."
            else
              # Create the label if it doesn't exist
              create_response=$(curl -s -X POST \
                -H "Authorization: token ${GITHUB_TOKEN}" \
                -d '{"name": "'"$label_name"'","color": "'"$label_color"'","description": "'"$label_description"'"}' \
                "${labels_url}")

              if [[ $(echo "$create_response" | jq -r '.name') == "$label_name" ]]; then
                echo "Label '${label_name}' created successfully in ${repo}."
              else
                echo "Failed to create label '${label_name}' in ${repo}. Error: $(echo $create_response | jq -r '.message')"
              fi
            fi
          done
        done
