name: Release

on:
  push:
    branches:
      - main

jobs:
  sync_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install -g github-label-sync

      - name: Sync labels with github-label-sync
        run: |
          npx github-label-sync --access-token ${{ secrets.GITHUB_TOKEN }} --labels ./labels.json ${{ github.repository }}
