name: Release

on:
  release:
    types: [published]

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install -y gh jq

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth login --with-token <<< "$GITHUB_TOKEN"

      - name: Apply Labels
        run: bash script/apply-labels.sh
