name: Release

# on:
#   release:
#     types: [published]

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  apply-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set permissions for script
        run: chmod +x script/apply-labels.sh

      - name: Run apply-labels.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: script/apply-labels.sh
