name: Update Labels to All Repositories

on:
  release:
    types: [published]

jobs:
  apply_labels:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Apply Labels to All Repositories
      env:
        GH_TOKEN: ${{ secrets.PELAGORNIS }}  # PAT Token
      run: |
        .github/scripts/update-all-labels.sh
